### ISSUE TITLE
Crashes instantly on Linux

### ISSUE THREAD

**Issue by lilithwhite** [p2sr/Portal2SpeedrunMod#12]
I did a fresh install and it seems that it crashes instantly on Linux (Pop_OS 22.04). I didn't install anything else. I installed Portal 2, launched it once then installed the speedrun mod, restarted steam and tried launching it, the splash screen shows up for about half a second and then I'm back in steam. I can't find any crash log or anything like that.

**Comment by Krzyhau** [comment]
Portal 2 had a small update recently, which completely ruined Linux support of all major plugins P2SR community has developed. That includes SourceAutoRecord, KrzyMod and SMSM - a plugin that Speedrun Mod uses. @mlugg already fixed most (if not all) of issues for SAR, so you can expect them fixing it in SMSM as well sometime in the near future.

**Comment by ThisAMJ** [comment]
Resolved by #13.

**Comment by randalthor17** [comment]
Is there a way to build P2SR for ourselves? There hasn't been a release since #13 and so the mod still crashes.

**Comment by betsruner** [comment]
Should have been resolved since Version 1.7 release in April. If it's not open another issue
